### ISSUE TITLE
An error in my Server log, I was wondering whats wrong on it

### ISSUE THREAD

**Issue by veploxmine123** [WarpKat/NoIntegrity.Org-Plugin-for-Unturned-LDM#1]
[loading] NoIntegrity
[registered] /bldel (NoIntegrity.Commands.CMD_BLDel/bldel)
[registered] /bladd (NoIntegrity.Commands.CMD_BLAdd/bladd)
[registered] /slotload (NoIntegrity.Commands.CMD_SlotLoad/slotload)
[registered] /slotsave (NoIntegrity.Commands.CMD_SlotSave/slotsave)
Could not find dependency: MySql.Data, Version=8.0.33.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
Could not find dependency: MySql.Data, Version=8.0.33.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
Failed to load NoIntegrity, unloading now... :System.IO.FileNotFoundException: Could not load file or assembly 'MySql.Data, Version=8.0.33.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies.
File name: 'MySql.Data, Version=8.0.33.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'
  at NoIntegrity.NoIntegrity.Load () [0x0001f] in <71aa581792064ed7a901de4a04df05d9>:0 
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00033] in <09b6a6e399e5417eb969381ca3201ce1>:0 

[unloading] NoIntegrity
NoIntegrity >> -- NoIntegrity 2024.2.22.0 has been unloaded.

**Comment by WarpKat** [comment]
It's missing the **MySql.Data.dll** from the Libraries directory.

If you don't have it, you will need it.

Go to the link below, download and copy this file into the Server/{your server}/Rocket/Libraries folder and restart your server.

https://github.com/WarpKat/NoIntegrity.Org-Plugin-for-Unturned-LDM/tree/master/Assets

**Comment by WarpKat** [comment]
Did this work for you?
